plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#']
  Exclude:
    - numo-optimize.gemspec

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/**/*'
