plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#']
  Exclude:
    - numo-optimize.gemspec

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 16

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/**/*'
