name: clang-format

on:
  push:
    branches:
      - main
      - dev*
    paths:
      - 'ext/**'
      - '.github/workflows/clang-format.yml'
  pull_request:
    paths:
      - 'ext/**'
      - '.github/workflows/clang-format.yml'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '18'
        check-path: 'ext'
