name: build

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  build-mac:
    runs-on: macos-latest
    name: Ruby 3.2 (asdf on macOS)
    steps:
      - uses: actions/checkout@v6
      - name: Set up asdf
        uses: asdf-vm/actions/setup@v4
      - name: Set up Ruby using asdf
        run: |
          asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
          asdf install ruby 3.2.2
          asdf set -u ruby 3.2.2
      - name: Run the default task
        run: |
          bundle install
          bundle exec rake
      - name: Install gem
        run: gem install numo-optimize
