name: rubocop

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: RuboCop
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop
